baseURL                = "https://homelab-alpha.nl"
defaultContentLanguage = "en"
disableAliases         = false
disableKinds           = ['rss']
enableEmoji            = true
enableGitInfo          = true
languageCode           = "en-NL"
timeZone               = "Europe/Amsterdam"
title                  = "Homelab-Alpha | Your gateway to Homelab-Alpha's open source documentation."

[build]
  noJSConfigInAssets = true

[module]
  [module.hugoVersion]
    extended = true
    min      = "0.100.0"

  [[module.imports]]
    path    = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
    disable = false

[taxonomies]
  category = 'categories'
  series   = 'series'
  tag      = 'tags'
  keyword  = 'keywords'
