defaultMarkdownHandler = "goldmark"

[highlight]
  codeFences = false
  lineNumbersInTable = true

[tableOfContents]
  endLevel = 3
  ordered = false
  startLevel = 1

[goldmark]
  [goldmark.renderer]
    hardWraps = false
    unsafe = true
    xhtml = false

  [goldmark.parser]
    autoHeadingID = true
    autoHeadingIDType = "github"

  [goldmark.parser.attribute]
    block = true
    title = true

  [goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = true
    strikethrough = true
    table = true
    taskList = true
    typographer = true

    [goldmark.extensions.passthrough]
    enable = true

      [goldmark.extensions.passthrough.delimiters]
        block = [['\[', '\]'], ['$$', '$$']]
        inline = [['\(', '\)']]
